logger:
  level: info
  formatter: json

http:
  addr: ":8080"
  handlers:

  - method: get
    path: "/api/v1/tickers/stream"
    type: stream
    stream:
      format: json
      consumer:
        format: json
        queue:
          type: nsq
          nsq:
            addr: 127.0.0.1:4150
            topic: ticker
            channel: platypus-tickers-stream
            consumerBufferSize: 128
      router:
        type: broadcast

  - method: get
    path: "/api/v1/tickers-changes/stream"
    type: streams
    streams:
      format: json
      consumers:
      - format: json
        queue:
          type: nsq
          nsq:
            addr: 127.0.0.1:4150
            topic: ticker
            channel: platypus-tc-streams
            consumerBufferSize: 128
      - format: json
        queue:
          type: nsq
          nsq:
            addr: 127.0.0.1:4150
            topic: change
            channel: platypus-tc-streams
            consumerBufferSize: 128
      wrap: >-
        {"type":"{{ .Consumer.Topic }}","payload":{{ .EventJSON }}}
      router:
        type: broadcast

  - method: get
    path: "/api/v1/tickers"
    type: latest
    latest:
      format: json
      consumer:
        format: json
        queue:
          type: nsq
          nsq:
            addr: 127.0.0.1:4150
            topic: ticker
            channel: platypus-tickers-latest
            consumerBufferSize: 128
      cache:
        key: |
          {{.market}}|{{(index .currencyPair 0).symbol}}|{{(index .currencyPair 1).symbol}}
        store:
          type: memoryttl
          memoryttl:
            ttl: 24h
            resolution: 1m

  # - Method: get
  #   Path: "/api/v1/tickers-changes"
  #   Type: latestfold
  #   LatestFold:
  #     Fold: |
  #       function (consumer, acc, v, k)
  #           local res = (acc or {})
  #           res[consumer.Nsq.Topic] = v
  #           return res
  #       end
  #     Consumers:
  #     - Type: nsq
  #       Format: json
  #       Nsq:
  #         Addr: 127.0.0.1:4150
  #         Topic: ticker
  #         Channel: platypus-latestfold
  #         ConsumerBufferSize: 128
  #         LogLevel: 1
  #     - Type: nsq
  #       Format: json
  #       Nsq:
  #         Addr: 127.0.0.1:4150
  #         Topic: change
  #         Channel: platypus-latestfold
  #         ConsumerBufferSize: 128
  #         LogLevel: 1
  #     Cache:
  #       Type: memoryttl
  #       Key:
  #         - .Market
  #         - .CurrencyPair[0].Symbol
  #         - .CurrencyPair[1].Symbol
