version: "2"
services:
  nsqd:
    image: nsqio/nsq
    command: >-
      /nsqd
      --broadcast-address=nsqd
      --lookupd-tcp-address=nsqlookupd:4160
      --tcp-address=0.0.0.0:4150
    ports:
      - "127.0.0.1:4150:4150"
      - "127.0.0.1:4151:4151"
    links:
      - "nsqlookupd:nsqlookupd"

  nsqlookupd:
    image: nsqio/nsq
    command: >-
      /nsqlookupd
      --tcp-address=0.0.0.0:4160
    ports:
      - "127.0.0.1:4160:4160"
      - "127.0.0.1:4161:4161"

  nsqadmin:
    image: nsqio/nsq
    command: >-
      /nsqadmin
      --lookupd-http-address=nsqlookupd:4161
      --http-address=0.0.0.0:4171
    ports:
      - "127.0.0.1:4170:4170"
      - "127.0.0.1:4171:4171"
    links:
      - "nsqlookupd:nsqlookupd"

  mole:
    image: cryptounicorns/mole
    volumes:
      - ./config.mole.json:/etc/mole/config.json
    command: >-
      /usr/bin/mole
      --config /etc/mole/config.json
      --debug
    links:
      - "nsqlookupd:nsqlookupd"
      - "nsqd:nsqd"

  platypus:
    image: cryptounicorns/platypus
    build: .
    volumes:
      - ./build/platypus:/usr/bin/platypus
      - ./config.json:/etc/platypus/config.json
    command: >-
      /usr/bin/platypus
      --config /etc/platypus/config.json
      --debug
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - "nsqlookupd:nsqlookupd"
      - "nsqd:nsqd"
