version: "2"
services:
  nsqd:
    image: nsqio/nsq
    command: >-
      /nsqd
      --broadcast-address=127.0.0.1
      --lookupd-tcp-address=127.0.0.1:4160
      --tcp-address=127.0.0.1:4150
    network_mode: host
  nsqlookupd:
    image: nsqio/nsq
    command: >-
      /nsqlookupd
      --tcp-address=127.0.0.1:4160
    network_mode: host
  nsqadmin:
    image: nsqio/nsq
    command: >-
      /nsqadmin
      --lookupd-http-address=127.0.0.1:4161
      --http-address=127.0.0.1:4171
    network_mode: host

  etcd:
    image: quay.io/coreos/etcd
    command: >-
      /usr/local/bin/etcd
      --log-output=stderr
      --debug
    network_mode: host
  zetcd:
    image: quay.io/coreos/zetcd
    # Entryponts sucks.
    command: >-
      --endpoints=127.0.0.1:2379
      --zkaddr=127.0.0.1:2181
    network_mode: host
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "tickers:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "127.0.0.1:2181"
    network_mode: host

  market-fetcher-http:
    image: cryptounicorns/market-fetcher-http
    build: .
    volumes:
      - ./build/market-fetcher-http:/usr/bin/market-fetcher-http
      - ./config.json:/etc/market-fetcher-http/config.json
    command: >-
      /usr/bin/market-fetcher-http
      --config /etc/market-fetcher-http/config.json
      --debug
    network_mode: host
